/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "nitroFrame/NitroFrame.h"
/* Header for class nps_nitroframe_lib_npNativeEvent */

#ifndef _Included_nps_nitroframe_lib_npNativeEvent
#define _Included_nps_nitroframe_lib_npNativeEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nps_nitroframe_lib_npNativeEvent
 * Method:    npSurfaceCreate
 * Signature: (IILjava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nps_nitroframe_lib_npNativeEvent_npSurfaceCreate
  (JNIEnv *env, jclass thiz, jint w, jint h,jobject assetManager, jstring apkPath);

/*
 * Class:     nps_nitroframe_lib_npNativeEvent
 * Method:    npSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_nps_nitroframe_lib_npNativeEvent_npSurfaceChanged
  (JNIEnv *env, jclass thiz, jint w, jint h);

/*
 * Class:     nps_nitroframe_lib_npNativeEvent
 * Method:    npUpdateGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nps_nitroframe_lib_npNativeEvent_npUpdateGame
  (JNIEnv *env, jclass thiz);

/*
 * Class:     nps_nitroframe_lib_npNativeEvent
 * Method:    npDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nps_nitroframe_lib_npNativeEvent_npDestroy
  (JNIEnv *env, jclass thiz);

/*
 * Class:     nps_nitroframe_lib_npNativeEvent
 * Method:    npRendering
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nps_nitroframe_lib_npNativeEvent_npRendering
  (JNIEnv *env, jclass thiz);

/*
 * Class:     nps_nitroframe_lib_npNativeEvent
 * Method:    npAndroidStatePause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nps_nitroframe_lib_npNativeEvent_npAndroidStatePause
  (JNIEnv *env, jclass thiz, jint);

/*
 * Class:     nps_nitroframe_lib_npNativeEvent
 * Method:    npOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nps_nitroframe_lib_npNativeEvent_npOnResume
  (JNIEnv *env, jclass thiz);

/*
 * Class:     nps_nitroframe_lib_npNativeEvent
 * Method:    npOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nps_nitroframe_lib_npNativeEvent_npOnPause
  (JNIEnv *env, jclass thiz);

#ifdef __cplusplus
}
#endif
#endif
